// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvejlxgckjjyucvoojps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2ZWpseGdja2pqeXVjdm9vanBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjMwMDksImV4cCI6MjA2MTQzOTAwOX0.ynG1FoioCZWl-IwLiStaCuozawbxoasth82ot2fIMas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);